name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/studio42gmbh/*" }]'
          servers: '[{ "id": "github", "username": "${env.USER}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
